name: docker-build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input for docker version tag such as: latest, v1.0.1'
        required: true
        type: string
      name:
        description: 'input for image repo name such as: cpp-env'
        required: true
        type: string
      path:
        description: 'input to Dockerfile within docker/ folder such as: Dockerfile'
        required: true
        type: string

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/${{ inputs.path }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.name }}:${{ inputs.version }}
          outputs: "type=registry"